version: '3.0'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:${keycloak_version:-latest}
    environment:
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Password1#
      DEBUG: true
      DEBUG_SUSPEND: n
      PRINT_ENV: true
      DEBUG_PORT: "*:8787"
      KC_LOG_LEVEL: DEBUG
    ports: [ "8080:8080", "8787:8787" ]
#    entrypoint:
#      - sh
#      - -c
#      - sleep 999999
    command:
#      - build
      - start-dev
    volumes:
      - ./target/dist:/opt/keycloak/providers
    working_dir: /opt/keycloak
